### ISSUE TITLE
zippo squat!

### ISSUE THREAD

**Issue by jasonwynn10** [MCUnderground/mcunderground.github.io#1]
There's nothing Here!!

**Comment by MCUnderground** [comment]
Ik! :+1:

**Comment by jasonwynn10** [comment]
I'm going to link the lostteam page to this site, so you may want to start work on it...
html5up.net gives some pretty cool templates

**Comment by jasonwynn10** [comment]
Finally starting to work on it?

**Comment by MCUnderground** [comment]
Yeah
but it redirects to my website, hosted with another shizzel
